version: "3.7"

services:
  mysql:
    container_name: mysql_server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - project_flask
  app_project:
    container_name: FlaskApp
    build:
      context: .
      dockerfile: Dockerfile
    image: projectflaskapp:1.0
    ports:
      - 5000:5000
    depends_on:
      - mysql
    networks:
      - project_flask

networks:
  project_flask:
    name: project_flask

